project:
  type: website
  output-dir: docs

website:
  title: "Dexter Howard"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "CV"
        file: Howard_fullCV.pdf        
      - icon: github
        href: https://github.com/dwh77
      - icon: linkedin
        href: https://www.linkedin.com/in/dexter-howard-593494199/

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false #to hid table of contents

editor: visual

